// Noms canoniques FR des exercices reconnus par l'app mobile (démos visuelles).
// Généré depuis nutrainer-native/src/data/exerciseDemos.js — sert à l'autocomplétion
// de l'éditeur de programme coach (un nom standard = démo garantie côté élève).
export const EXERCISE_NAMES = [
  "Ab wheel",
  "Abduction machine",
  "Adduction machine",
  "Adduction poulie",
  "Arraché",
  "Barre au front",
  "Battements de jambes",
  "Box squat",
  "Ciseaux",
  "Corde à sauter",
  "Crunch",
  "Crunch à la poulie",
  "Crunch bicyclette",
  "Crunch décliné",
  "Crunch inversé",
  "Crunch oblique",
  "Crunch swiss ball",
  "Curl à la poulie",
  "Curl alterné",
  "Curl barre",
  "Curl barre ez",
  "Curl concentré",
  "Curl haltères",
  "Curl incliné",
  "Curl inversé",
  "Curl machine",
  "Curl marteau",
  "Curl marteau à la corde",
  "Curl poignets",
  "Curl pupitre",
  "Curl zottman",
  "Dead bug",
  "Développé à la poulie",
  "Développé arnold",
  "Développé assis haltères",
  "Développé couché",
  "Développé couché haltères",
  "Développé couché prise serrée",
  "Développé couché smith",
  "Développé décliné",
  "Développé décliné haltères",
  "Développé épaules barre",
  "Développé épaules haltères",
  "Développé épaules machine",
  "Développé incliné",
  "Développé incliné haltères",
  "Développé machine",
  "Développé militaire",
  "Développé militaire assis",
  "Dips",
  "Dips barres parallèles",
  "Dips entre bancs",
  "Dips pectoraux",
  "Écarté à la poulie",
  "Écarté couché",
  "Écarté couché à la poulie",
  "Écarté incliné",
  "Écarté incliné poulie",
  "Écarté poulie basse",
  "Élévations frontales",
  "Élévations frontales disque",
  "Élévations latérales",
  "Élévations latérales poulie",
  "Épaulé",
  "Épaulé jeté",
  "Extension triceps à la corde",
  "Extension triceps assis",
  "Extension triceps corde au dessus de la tête",
  "Extension triceps couché",
  "Extension triceps couché haltères",
  "Extension triceps haltère",
  "Extension triceps machine",
  "Extension triceps poulie haute",
  "Extensions lombaires",
  "Extensions mollets debout",
  "Face pull",
  "Fentes",
  "Fentes arrière",
  "Fentes barre",
  "Fentes marchées",
  "Fentes marchées barre",
  "Front squat",
  "Gainage",
  "Gainage latéral",
  "Glute ham raise",
  "Goblet squat",
  "Good morning",
  "Hack squat",
  "Hip thrust",
  "Hyperextension inversée",
  "Kettlebell swing",
  "Kickback fessier",
  "Kickback fessier poulie",
  "Kickback triceps",
  "Leg curl",
  "Leg curl assis",
  "Leg curl debout",
  "Leg extension",
  "Leg press",
  "Marche du fermier",
  "Mollets à la presse",
  "Mollets assis",
  "Mollets debout barre",
  "Mollets debout haltères",
  "Mollets donkey",
  "Mountain climbers",
  "Muscle up",
  "Oiseau",
  "Oiseau à la machine",
  "Oiseau assis",
  "Overhead squat",
  "Pallof press",
  "Pec deck",
  "Pistol squat",
  "Pompes",
  "Pompes déclinées",
  "Pompes inclinées",
  "Pompes prise large",
  "Pompes verticales",
  "Pont fessier",
  "Pont fessier barre",
  "Pont fessier une jambe",
  "Pull over",
  "Push press",
  "Pushdown prise inversée",
  "Rameur",
  "Relevés de genoux",
  "Relevés de jambes",
  "Relevés de jambes suspendu",
  "Rowing barre",
  "Rowing haltère un bras",
  "Rowing haltères",
  "Rowing inversé",
  "Rowing machine",
  "Rowing menton",
  "Rowing smith",
  "Rowing t bar",
  "Russian twist",
  "Shrugs barre",
  "Shrugs haltères",
  "Sit up",
  "Soulevé de terre",
  "Soulevé de terre jambes tendues",
  "Soulevé de terre jambes tendues haltères",
  "Soulevé de terre roumain",
  "Soulevé de terre sumo",
  "Soulevé de terre trap bar",
  "Soulevé de terre une jambe",
  "Spider curl",
  "Split squat",
  "Squat",
  "Squat bulgare",
  "Squat bulgare barre",
  "Squat complet",
  "Squat haltères",
  "Squat poids du corps",
  "Squat sauté",
  "Squat smith",
  "Squat sumo",
  "Squat zercher",
  "Step up",
  "Step up barre",
  "Superman",
  "Thruster",
  "Tirage bras tendus",
  "Tirage horizontal",
  "Tirage nuque",
  "Tirage vertical",
  "Tirage vertical prise neutre",
  "Tirage vertical prise serrée",
  "Tirage vertical supination",
  "Tractions",
  "Tractions supination",
];
