// Noms canoniques FR des exercices reconnus par l'app mobile (démos visuelles).
// Généré depuis nutrainer-native/src/data/exerciseDemos.js — sert à l'autocomplétion
// de l'éditeur de programme coach (un nom standard = démo garantie côté élève).
export const EXERCISE_NAMES = [
  "Ab wheel",
  "Abduction machine",
  "Adduction machine",
  "Adduction poulie",
  "Arraché",
  "Barre au front",
  "Battements de jambes",
  "Box squat",
  "Ciseaux",
  "Corde à sauter",
  "Crunch",
  "Crunch à la poulie",
  "Crunch bicyclette",
  "Crunch décliné",
  "Crunch inversé",
  "Crunch oblique",
  "Crunch swiss ball",
  "Curl à la poulie",
  "Curl alterné",
  "Curl barre",
  "Curl barre ez",
  "Curl concentré",
  "Curl haltères",
  "Curl incliné",
  "Curl inversé",
  "Curl machine",
  "Curl marteau",
  "Curl marteau à la corde",
  "Curl poignets",
  "Curl pupitre",
  "Curl zottman",
  "Dead bug",
  "Développé à la poulie",
  "Développé arnold",
  "Développé assis haltères",
  "Développé couché",
  "Développé couché haltères",
  "Développé couché prise serrée",
  "Développé couché smith",
  "Développé décliné",
  "Développé décliné haltères",
  "Développé épaules barre",
  "Développé épaules haltères",
  "Développé épaules machine",
  "Développé incliné",
  "Développé incliné haltères",
  "Développé machine",
  "Développé militaire",
  "Développé militaire assis",
  "Dips",
  "Dips barres parallèles",
  "Dips entre bancs",
  "Dips pectoraux",
  "Écarté à la poulie",
  "Écarté couché",
  "Écarté couché à la poulie",
  "Écarté incliné",
  "Écarté incliné poulie",
  "Écarté poulie basse",
  "Élévations frontales",
  "Élévations frontales disque",
  "Élévations latérales",
  "Élévations latérales poulie",
  "Épaulé",
  "Épaulé jeté",
  "Extension triceps à la corde",
  "Extension triceps assis",
  "Extension triceps corde au dessus de la tête",
  "Extension triceps couché",
  "Extension triceps couché haltères",
  "Extension triceps haltère",
  "Extension triceps machine",
  "Extension triceps poulie haute",
  "Extensions lombaires",
  "Extensions mollets debout",
  "Face pull",
  "Fentes",
  "Fentes arrière",
  "Fentes barre",
  "Fentes marchées",
  "Fentes marchées barre",
  "Front squat",
  "Gainage",
  "Gainage latéral",
  "Glute ham raise",
  "Goblet squat",
  "Good morning",
  "Hack squat",
  "Hip thrust",
  "Hyperextension inversée",
  "Kettlebell swing",
  "Kickback fessier",
  "Kickback fessier poulie",
  "Kickback triceps",
  "Leg curl",
  "Leg curl assis",
  "Leg curl debout",
  "Leg extension",
  "Leg press",
  "Marche du fermier",
  "Mollets à la presse",
  "Mollets assis",
  "Mollets debout barre",
  "Mollets debout haltères",
  "Mollets donkey",
  "Mountain climbers",
  "Muscle up",
  "Oiseau",
  "Oiseau à la machine",
  "Oiseau assis",
  "Overhead squat",
  "Pallof press",
  "Pec deck",
  "Pistol squat",
  "Pompes",
  "Pompes déclinées",
  "Pompes inclinées",
  "Pompes prise large",
  "Pompes verticales",
  "Pont fessier",
  "Pont fessier barre",
  "Pont fessier une jambe",
  "Pull over",
  "Push press",
  "Pushdown prise inversée",
  "Rameur",
  "Relevés de genoux",
  "Relevés de jambes",
  "Relevés de jambes suspendu",
  "Rowing barre",
  "Rowing haltère un bras",
  "Rowing haltères",
  "Rowing inversé",
  "Rowing machine",
  "Rowing menton",
  "Rowing smith",
  "Rowing t bar",
  "Russian twist",
  "Shrugs barre",
  "Shrugs haltères",
  "Sit up",
  "Soulevé de terre",
  "Soulevé de terre jambes tendues",
  "Soulevé de terre jambes tendues haltères",
  "Soulevé de terre roumain",
  "Soulevé de terre sumo",
  "Soulevé de terre trap bar",
  "Soulevé de terre une jambe",
  "Spider curl",
  "Split squat",
  "Squat",
  "Squat bulgare",
  "Squat bulgare barre",
  "Squat complet",
  "Squat haltères",
  "Squat poids du corps",
  "Squat sauté",
  "Squat smith",
  "Squat sumo",
  "Squat zercher",
  "Step up",
  "Step up barre",
  "Superman",
  "Thruster",
  "Tirage bras tendus",
  "Tirage horizontal",
  "Tirage nuque",
  "Tirage vertical",
  "Tirage vertical prise neutre",
  "Tirage vertical prise serrée",
  "Tirage vertical supination",
  "Tractions",
  "Tractions supination",
];

// Vocabulaire ANGLAIS (lingo muscu standard), aligné INDEX PAR INDEX avec EXERCISE_NAMES
// (EXERCISE_NAMES_EN[i] = traduction de EXERCISE_NAMES[i]) — permet un mapping bidirectionnel.
// Sert de vocabulaire de contrainte pour les générations IA non francophones.
export const EXERCISE_NAMES_EN = [
  "Ab wheel rollout",
  "Hip abduction machine",
  "Hip adduction machine",
  "Cable hip adduction",
  "Snatch",
  "Skull crusher",
  "Flutter kicks",
  "Box squat",
  "Scissor kicks",
  "Jump rope",
  "Crunch",
  "Cable crunch",
  "Bicycle crunch",
  "Decline crunch",
  "Reverse crunch",
  "Oblique crunch",
  "Swiss ball crunch",
  "Cable curl",
  "Alternating dumbbell curl",
  "Barbell curl",
  "EZ-bar curl",
  "Concentration curl",
  "Dumbbell curl",
  "Incline dumbbell curl",
  "Reverse curl",
  "Machine curl",
  "Hammer curl",
  "Rope hammer curl",
  "Wrist curl",
  "Preacher curl",
  "Zottman curl",
  "Dead bug",
  "Cable chest press",
  "Arnold press",
  "Seated dumbbell press",
  "Bench press",
  "Dumbbell bench press",
  "Close-grip bench press",
  "Smith machine bench press",
  "Decline bench press",
  "Decline dumbbell press",
  "Barbell shoulder press",
  "Dumbbell shoulder press",
  "Machine shoulder press",
  "Incline bench press",
  "Incline dumbbell press",
  "Machine chest press",
  "Overhead press",
  "Seated military press",
  "Dips",
  "Parallel bar dips",
  "Bench dips",
  "Chest dips",
  "Cable fly",
  "Dumbbell fly",
  "Lying cable fly",
  "Incline dumbbell fly",
  "Incline cable fly",
  "Low cable fly",
  "Front raise",
  "Plate front raise",
  "Lateral raise",
  "Cable lateral raise",
  "Clean",
  "Clean and jerk",
  "Rope triceps pushdown",
  "Seated triceps extension",
  "Overhead rope triceps extension",
  "Lying triceps extension",
  "Lying dumbbell triceps extension",
  "Dumbbell triceps extension",
  "Machine triceps extension",
  "Cable triceps pushdown",
  "Back extension",
  "Standing calf raise",
  "Face pull",
  "Lunges",
  "Reverse lunges",
  "Barbell lunges",
  "Walking lunges",
  "Barbell walking lunges",
  "Front squat",
  "Plank",
  "Side plank",
  "Glute ham raise",
  "Goblet squat",
  "Good morning",
  "Hack squat",
  "Hip thrust",
  "Reverse hyperextension",
  "Kettlebell swing",
  "Glute kickback",
  "Cable glute kickback",
  "Triceps kickback",
  "Leg curl",
  "Seated leg curl",
  "Standing leg curl",
  "Leg extension",
  "Leg press",
  "Farmer's walk",
  "Leg press calf raise",
  "Seated calf raise",
  "Barbell standing calf raise",
  "Dumbbell standing calf raise",
  "Donkey calf raise",
  "Mountain climbers",
  "Muscle up",
  "Bent-over reverse fly",
  "Reverse pec deck",
  "Seated reverse fly",
  "Overhead squat",
  "Pallof press",
  "Pec deck",
  "Pistol squat",
  "Push-ups",
  "Decline push-ups",
  "Incline push-ups",
  "Wide-grip push-ups",
  "Handstand push-ups",
  "Glute bridge",
  "Barbell glute bridge",
  "Single-leg glute bridge",
  "Pullover",
  "Push press",
  "Reverse-grip pushdown",
  "Rower",
  "Knee raises",
  "Leg raises",
  "Hanging leg raises",
  "Barbell row",
  "One-arm dumbbell row",
  "Dumbbell row",
  "Inverted row",
  "Machine row",
  "Upright row",
  "Smith machine row",
  "T-bar row",
  "Russian twist",
  "Barbell shrugs",
  "Dumbbell shrugs",
  "Sit-up",
  "Deadlift",
  "Stiff-leg deadlift",
  "Dumbbell stiff-leg deadlift",
  "Romanian deadlift",
  "Sumo deadlift",
  "Trap bar deadlift",
  "Single-leg deadlift",
  "Spider curl",
  "Split squat",
  "Squat",
  "Bulgarian split squat",
  "Barbell Bulgarian split squat",
  "Deep squat",
  "Dumbbell squat",
  "Bodyweight squat",
  "Jump squat",
  "Smith machine squat",
  "Sumo squat",
  "Zercher squat",
  "Step-up",
  "Barbell step-up",
  "Superman",
  "Thruster",
  "Straight-arm pulldown",
  "Seated cable row",
  "Behind-the-neck pulldown",
  "Lat pulldown",
  "Neutral-grip lat pulldown",
  "Close-grip lat pulldown",
  "Underhand lat pulldown",
  "Pull-ups",
  "Chin-ups",
];

// Vocabulaire de contrainte selon la langue de GÉNÉRATION du programme.
// fr → liste canonique FR (démos mobiles garanties) ; autres langues → liste EN
// (lingo muscu international, compréhensible aussi pour es/de/pt/it).
export function exerciseNamesFor(lang) {
  return lang === 'fr' ? EXERCISE_NAMES : EXERCISE_NAMES_EN;
}
