// Textes serveur visibles par l'utilisateur final (pushes web/Expo, erreurs affichées
// par l'app, templates par défaut). Langues : fr (défaut/fallback), en, es.
//
// Usage : pushText(lang, key, vars) — interpolation {{var}} simple.
// La langue est TOUJOURS celle du DESTINATAIRE (getUserLang(destinataire) pour les
// pushes/crons, detectLang(req) pour les erreurs renvoyées à l'appelant).
//
// RÈGLE : les textes fr doivent rester STRICTEMENT identiques aux anciens textes en dur
// quand ils servent aussi à détecter un contenu « par défaut » (welcome_day*, labels
// checkin_label_*) — ne pas les reformuler sans adapter la détection.

export const PUSH_TEXTS = {
  fr: {
    // ── Rappels de log quotidiens (élève) ──
    reminder_early_1_title: '🥗 Ton journal t\'attend',
    reminder_early_1_body: 'Quelques secondes suffisent pour logger ta journée. On s\'y remet ?',
    reminder_early_2_title: '👋 Petit coucou de ton suivi',
    reminder_early_2_body: 'Un repas loggé, c\'est déjà une victoire. Lance-toi !',
    reminder_early_3_title: '📒 On reprend le fil ?',
    reminder_early_3_body: 'Ajoute ton dernier repas, ça prend moins de 30 secondes.',
    reminder_early_4_title: '🌟 Ta régularité fait la différence',
    reminder_early_4_body: 'Logger aujourd\'hui, c\'est garder ton élan. Tu gères !',
    reminder_early_5_title: '🍽 Un repas à noter ?',
    reminder_early_5_body: 'Ton journal est tout prêt — quelques secondes et c\'est fait.',
    reminder_streak_title: '🔥 Ta série de {{streak}} jours est en jeu !',
    reminder_streak_body: 'Logge un repas avant minuit pour la garder vivante.',
    reminder_late_title: '🥗 {{days}} jours sans log — on s\'y remet ?',
    reminder_goal_left_body: 'Il te reste {{remaining}} kg vers ton objectif de {{goalWeight}} kg. Chaque jour loggé te rapproche !',
    reminder_goal_reached_body: 'Tu étais à ton objectif de {{goalWeight}} kg — reviens logger pour le garder !',
    reminder_generic_body: 'Reviens logger un repas, ton suivi reprend là où tu l\'as laissé.',

    // ── Séance du jour / brief matinal (élève) ──
    session_today_title: '💪 Au programme aujourd\'hui : {{label}}',
    session_today_body: 'Programmé par ton coach — bonne séance !',
    morning_title: '✦ Bonjour {{prenom}} !',
    morning_title_generic: '✦ Coach IA',

    // ── Check-in & photo hebdo (élève) ──
    checkin_reminder_title: '✅ Check-in de la semaine',
    checkin_reminder_body: 'Ton coach attend ton retour hebdomadaire',
    photo_reminder_title: '📸 Photo de suivi',
    photo_reminder_body: 'Envoie ta photo de progression de la semaine à ton coach.',

    // ── Notifications élève ← actions coach ──
    coach_program_sent_body: 'Ton plan nutritionnel est prêt !',
    coach_muscu_sent_body: 'Ton programme de musculation est prêt !',
    coach_report_sent_body: 'Ton bilan nutritionnel est disponible !',
    journal_comment_body: 'a commenté ton journal',
    media_comment_title: '💬 Ton coach a réagi à ta photo',
    blood_ready_title: '🩸 Ton bilan est prêt',
    blood_ready_body: '{{name}} a analysé ton bilan sanguin',
    blood_analyzed_body: 'Ton bilan sanguin a été analysé',
    goals_updated_body: 'Tes objectifs nutritionnels ont été mis à jour',
    coach_removed_title: '🎁 7 jours Pro offerts',
    coach_removed_body: 'Ton suivi coach a pris fin — profite de 7 jours Pro, puis abonne-toi pour garder toutes les fonctionnalités.',

    // ── Bilans auto & rapports (élève) ──
    weekly_report_ready_title: '📊 Bilan hebdomadaire prêt',
    weekly_report_ready_body: 'Ton bilan de la semaine est disponible dans Santé',
    monthly_report_ready_title: '📊 Bilan mensuel prêt',
    monthly_report_ready_body: 'Ton bilan du mois est disponible dans Santé',
    weekly_report_entry_title: 'Bilan semaine du {{date}}',
    monthly_report_entry_title: 'Bilan {{month}}',
    report_type_health: 'Analyse de bilans',
    report_type_nutrition: 'Rapport nutritionnel {{days}}j',
    report_self_ready_title: '📄 {{title}} prêt',
    report_self_ready_body: 'Appuie pour consulter ton rapport',
    program_ready_muscu_title: '⚡ Programme muscu généré !',
    program_ready_muscu_body: 'Ton plan d\'entraînement est prêt.',
    program_ready_nutrition_title: '⚡ Programme nutritionnel généré !',
    program_ready_nutrition_body: 'Ton plan alimentaire est prêt.',

    // ── Notifications coach ← activité élèves ──
    new_athlete_title: '🎉 Nouvel élève !',
    new_athlete_body: '{{prenom}} vient de rejoindre ton coaching.',
    intake_received_title: '📋 Questionnaire reçu',
    intake_received_body: '{{name}} a rempli son questionnaire',
    checkin_received_title: '✅ Check-in reçu',
    checkin_received_body: '{{name}} a fait son check-in',
    blood_new_title: '🩸 Nouveau bilan sanguin',
    blood_new_body: '{{name}} a envoyé un bilan à analyser',
    media_new_photo_title: '📸 Photo de {{name}}',
    media_new_video_title: '🎥 Vidéo de {{name}}',
    media_new_body: 'Nouveau suivi à consulter',
    report_request_title: '📄 Demande de bilan',
    report_request_body: '{{name}} demande un rapport nutritionnel',
    inactive_athlete_title: '{{prenom}} n\'a rien loggé depuis 7 jours',
    inactive_athlete_body: 'Un message de ta part peut relancer son suivi.',
    program_draft_ready_title: '🥗 Programme prêt pour {{name}}',
    muscu_draft_ready_title: '💪 Programme muscu prêt pour {{name}}',
    draft_ready_body: 'Reviens sur le tableau de bord pour réviser et envoyer',
    coach_report_ready_title: '📄 Rapport de {{name}} prêt',
    coach_report_ready_body: 'Appuie pour consulter le rapport',
    coach_digest_title: '☀️ Ta journée coach',
    digest_reports_one: '{{n}} bilan à valider',
    digest_reports_many: '{{n}} bilans à valider',
    digest_media_one: '{{n}} nouveau média',
    digest_media_many: '{{n}} nouveaux médias',
    digest_messages_one: '{{n}} message',
    digest_messages_many: '{{n}} messages',
    digest_inactive_one: '{{n}} élève inactif',
    digest_inactive_many: '{{n}} élèves inactifs',

    // ── Séquence de bienvenue PAR DÉFAUT (messages « du coach » → élève).
    // fr = texte par défaut historique EXACT (sert à détecter un step non personnalisé).
    welcome_day0: "Bienvenue à bord ! 💪 Je suis ravi de t'accompagner. Prends le temps de découvrir l'app tranquillement, et surtout écris-moi ici dès que tu as une question : je suis là pour toi. On avance ensemble !",
    welcome_day2: "Hello ! J'espère que tu prends bien tes marques 😊 Pense à compléter ton questionnaire et à enregistrer tes premiers repas et entraînements : plus j'en sais sur toi, mieux je peux adapter ton suivi. À très vite !",
    welcome_day7: "Déjà une semaine ensemble ! 🎉 Dis-moi comment tu te sens : ton énergie, tes repas, tes séances… Raconte-moi tout, on fait un premier point et on ajuste ce qu'il faut pour la suite.",

    // ── Template de check-in PAR DÉFAUT (labels affichés à l'élève) ──
    checkin_label_mood: 'Humeur',
    checkin_label_energy: 'Énergie',
    checkin_label_sleep: 'Sommeil (h/nuit)',
    checkin_label_weight: 'Poids',
    checkin_label_notes: 'Notes libres',

    // ── Erreurs affichées telles quelles par l'app ──
    err_too_many_requests: 'Trop de requêtes, réessaie dans un moment',
    err_too_many_attempts: 'Trop de tentatives, réessaie dans une minute',
    err_too_many_signups: 'Trop de créations de comptes depuis cette IP',
    err_too_many_resets: 'Trop de demandes, réessaie dans une heure',
    err_email_send: 'Erreur lors de l\'envoi de l\'email. Réessaie dans quelques instants.',
    err_generation: 'Génération impossible, réessaie.',
    coach_managed_ai: 'Tu as un coach — contacte-le directement.',
    coach_managed_nutrition: 'Ton coach gère ton programme nutritionnel.',
    coach_managed_muscu: 'Ton coach gère ton programme d\'entraînement.',
    coach_managed_recipes: 'Ton coach gère tes recettes.',
    coach_required_report: 'Demande ton rapport à ton coach.',
  },

  en: {
    reminder_early_1_title: '🥗 Your journal is waiting',
    reminder_early_1_body: 'Logging your day takes just a few seconds. Ready to jump back in?',
    reminder_early_2_title: '👋 A little nudge from your tracker',
    reminder_early_2_body: 'One logged meal is already a win. Go for it!',
    reminder_early_3_title: '📒 Pick up where you left off?',
    reminder_early_3_body: 'Add your last meal — it takes less than 30 seconds.',
    reminder_early_4_title: '🌟 Consistency makes the difference',
    reminder_early_4_body: 'Logging today keeps your momentum going. You\'ve got this!',
    reminder_early_5_title: '🍽 A meal to log?',
    reminder_early_5_body: 'Your journal is ready — a few seconds and you\'re done.',
    reminder_streak_title: '🔥 Your {{streak}}-day streak is on the line!',
    reminder_streak_body: 'Log a meal before midnight to keep it alive.',
    reminder_late_title: '🥗 {{days}} days without logging — back at it?',
    reminder_goal_left_body: 'You\'re {{remaining}} kg away from your {{goalWeight}} kg goal. Every logged day gets you closer!',
    reminder_goal_reached_body: 'You were at your {{goalWeight}} kg goal — come back and log to keep it!',
    reminder_generic_body: 'Come back and log a meal — your tracking picks up right where you left off.',

    session_today_title: '💪 On the schedule today: {{label}}',
    session_today_body: 'Planned by your coach — have a great workout!',
    morning_title: '✦ Good morning {{prenom}}!',
    morning_title_generic: '✦ AI Coach',

    checkin_reminder_title: '✅ Weekly check-in',
    checkin_reminder_body: 'Your coach is waiting for your weekly update',
    photo_reminder_title: '📸 Progress photo',
    photo_reminder_body: 'Send this week\'s progress photo to your coach.',

    coach_program_sent_body: 'Your nutrition plan is ready!',
    coach_muscu_sent_body: 'Your training program is ready!',
    coach_report_sent_body: 'Your nutrition report is available!',
    journal_comment_body: 'commented on your journal',
    media_comment_title: '💬 Your coach reacted to your photo',
    blood_ready_title: '🩸 Your blood test is ready',
    blood_ready_body: '{{name}} analyzed your blood test',
    blood_analyzed_body: 'Your blood test has been analyzed',
    goals_updated_body: 'Your nutrition goals have been updated',
    coach_removed_title: '🎁 7 days of Pro, on us',
    coach_removed_body: 'Your coaching has ended — enjoy 7 days of Pro, then subscribe to keep all the features.',

    weekly_report_ready_title: '📊 Weekly report ready',
    weekly_report_ready_body: 'Your weekly report is available in Health',
    monthly_report_ready_title: '📊 Monthly report ready',
    monthly_report_ready_body: 'Your monthly report is available in Health',
    weekly_report_entry_title: 'Weekly report — {{date}}',
    monthly_report_entry_title: 'Report — {{month}}',
    report_type_health: 'Blood test analysis',
    report_type_nutrition: '{{days}}-day nutrition report',
    report_self_ready_title: '📄 {{title}} ready',
    report_self_ready_body: 'Tap to view your report',
    program_ready_muscu_title: '⚡ Training program generated!',
    program_ready_muscu_body: 'Your training plan is ready.',
    program_ready_nutrition_title: '⚡ Nutrition program generated!',
    program_ready_nutrition_body: 'Your meal plan is ready.',

    new_athlete_title: '🎉 New client!',
    new_athlete_body: '{{prenom}} just joined your coaching.',
    intake_received_title: '📋 Questionnaire received',
    intake_received_body: '{{name}} filled in their questionnaire',
    checkin_received_title: '✅ Check-in received',
    checkin_received_body: '{{name}} completed their check-in',
    blood_new_title: '🩸 New blood test',
    blood_new_body: '{{name}} sent a blood test to review',
    media_new_photo_title: '📸 Photo from {{name}}',
    media_new_video_title: '🎥 Video from {{name}}',
    media_new_body: 'New progress update to review',
    report_request_title: '📄 Report request',
    report_request_body: '{{name}} is requesting a nutrition report',
    inactive_athlete_title: '{{prenom}} hasn\'t logged anything in 7 days',
    inactive_athlete_body: 'A message from you could get them back on track.',
    program_draft_ready_title: '🥗 Program ready for {{name}}',
    muscu_draft_ready_title: '💪 Training program ready for {{name}}',
    draft_ready_body: 'Head back to the dashboard to review and send',
    coach_report_ready_title: '📄 {{name}}\'s report is ready',
    coach_report_ready_body: 'Tap to view the report',
    coach_digest_title: '☀️ Your coaching day',
    digest_reports_one: '{{n}} test to review',
    digest_reports_many: '{{n}} tests to review',
    digest_media_one: '{{n}} new media',
    digest_media_many: '{{n}} new media',
    digest_messages_one: '{{n}} message',
    digest_messages_many: '{{n}} messages',
    digest_inactive_one: '{{n}} inactive client',
    digest_inactive_many: '{{n}} inactive clients',

    welcome_day0: "Welcome aboard! 💪 I'm really glad to be working with you. Take your time exploring the app, and message me here whenever you have a question — I'm here for you. Let's do this together!",
    welcome_day2: "Hey! I hope you're settling in nicely 😊 Remember to complete your questionnaire and log your first meals and workouts: the more I know about you, the better I can tailor your coaching. Talk soon!",
    welcome_day7: "One week together already! 🎉 Tell me how you're feeling: your energy, your meals, your workouts… Tell me everything — let's do a first review and adjust whatever's needed going forward.",

    checkin_label_mood: 'Mood',
    checkin_label_energy: 'Energy',
    checkin_label_sleep: 'Sleep (h/night)',
    checkin_label_weight: 'Weight',
    checkin_label_notes: 'Notes',

    err_too_many_requests: 'Too many requests — try again in a moment',
    err_too_many_attempts: 'Too many attempts — try again in a minute',
    err_too_many_signups: 'Too many accounts created from this IP',
    err_too_many_resets: 'Too many requests — try again in an hour',
    err_email_send: 'Something went wrong sending the email. Try again in a moment.',
    err_generation: 'Generation failed — please try again.',
    coach_managed_ai: 'You have a coach — reach out to them directly.',
    coach_managed_nutrition: 'Your coach manages your nutrition program.',
    coach_managed_muscu: 'Your coach manages your training program.',
    coach_managed_recipes: 'Your coach manages your recipes.',
    coach_required_report: 'Ask your coach for your report.',
  },

  es: {
    reminder_early_1_title: '🥗 Tu diario te espera',
    reminder_early_1_body: 'Registrar tu día solo toma unos segundos. ¿Volvemos a ello?',
    reminder_early_2_title: '👋 Un saludito de tu seguimiento',
    reminder_early_2_body: 'Una comida registrada ya es una victoria. ¡Anímate!',
    reminder_early_3_title: '📒 ¿Retomamos el hilo?',
    reminder_early_3_body: 'Añade tu última comida, toma menos de 30 segundos.',
    reminder_early_4_title: '🌟 Tu constancia marca la diferencia',
    reminder_early_4_body: 'Registrar hoy es mantener tu impulso. ¡Tú puedes!',
    reminder_early_5_title: '🍽 ¿Una comida que anotar?',
    reminder_early_5_body: 'Tu diario está listo — unos segundos y ya está.',
    reminder_streak_title: '🔥 ¡Tu racha de {{streak}} días está en juego!',
    reminder_streak_body: 'Registra una comida antes de medianoche para mantenerla viva.',
    reminder_late_title: '🥗 {{days}} días sin registrar — ¿volvemos?',
    reminder_goal_left_body: 'Te quedan {{remaining}} kg hasta tu objetivo de {{goalWeight}} kg. ¡Cada día registrado te acerca!',
    reminder_goal_reached_body: 'Estabas en tu objetivo de {{goalWeight}} kg — ¡vuelve a registrar para mantenerlo!',
    reminder_generic_body: 'Vuelve a registrar una comida, tu seguimiento continúa donde lo dejaste.',

    session_today_title: '💪 En el programa de hoy: {{label}}',
    session_today_body: 'Programado por tu coach — ¡buen entrenamiento!',
    morning_title: '✦ ¡Buenos días {{prenom}}!',
    morning_title_generic: '✦ Coach IA',

    checkin_reminder_title: '✅ Check-in de la semana',
    checkin_reminder_body: 'Tu coach espera tu resumen semanal',
    photo_reminder_title: '📸 Foto de seguimiento',
    photo_reminder_body: 'Envía a tu coach tu foto de progreso de la semana.',

    coach_program_sent_body: '¡Tu plan de nutrición está listo!',
    coach_muscu_sent_body: '¡Tu programa de entrenamiento está listo!',
    coach_report_sent_body: '¡Tu informe nutricional está disponible!',
    journal_comment_body: 'comentó tu diario',
    media_comment_title: '💬 Tu coach reaccionó a tu foto',
    blood_ready_title: '🩸 Tu análisis está listo',
    blood_ready_body: '{{name}} analizó tu análisis de sangre',
    blood_analyzed_body: 'Tu análisis de sangre ha sido analizado',
    goals_updated_body: 'Tus objetivos nutricionales han sido actualizados',
    coach_removed_title: '🎁 7 días Pro de regalo',
    coach_removed_body: 'Tu seguimiento con coach ha terminado — disfruta 7 días Pro y luego suscríbete para conservar todas las funciones.',

    weekly_report_ready_title: '📊 Informe semanal listo',
    weekly_report_ready_body: 'Tu informe de la semana está disponible en Salud',
    monthly_report_ready_title: '📊 Informe mensual listo',
    monthly_report_ready_body: 'Tu informe del mes está disponible en Salud',
    weekly_report_entry_title: 'Informe semana del {{date}}',
    monthly_report_entry_title: 'Informe {{month}}',
    report_type_health: 'Análisis de resultados',
    report_type_nutrition: 'Informe nutricional {{days}}d',
    report_self_ready_title: '📄 {{title}} listo',
    report_self_ready_body: 'Toca para ver tu informe',
    program_ready_muscu_title: '⚡ ¡Programa de entrenamiento generado!',
    program_ready_muscu_body: 'Tu plan de entrenamiento está listo.',
    program_ready_nutrition_title: '⚡ ¡Programa nutricional generado!',
    program_ready_nutrition_body: 'Tu plan de comidas está listo.',

    new_athlete_title: '🎉 ¡Nuevo alumno!',
    new_athlete_body: '{{prenom}} acaba de unirse a tu coaching.',
    intake_received_title: '📋 Cuestionario recibido',
    intake_received_body: '{{name}} completó su cuestionario',
    checkin_received_title: '✅ Check-in recibido',
    checkin_received_body: '{{name}} hizo su check-in',
    blood_new_title: '🩸 Nuevo análisis de sangre',
    blood_new_body: '{{name}} envió un análisis para revisar',
    media_new_photo_title: '📸 Foto de {{name}}',
    media_new_video_title: '🎥 Vídeo de {{name}}',
    media_new_body: 'Nuevo seguimiento por revisar',
    report_request_title: '📄 Solicitud de informe',
    report_request_body: '{{name}} solicita un informe nutricional',
    inactive_athlete_title: '{{prenom}} no ha registrado nada en 7 días',
    inactive_athlete_body: 'Un mensaje tuyo puede reactivar su seguimiento.',
    program_draft_ready_title: '🥗 Programa listo para {{name}}',
    muscu_draft_ready_title: '💪 Programa de entrenamiento listo para {{name}}',
    draft_ready_body: 'Vuelve al panel para revisar y enviar',
    coach_report_ready_title: '📄 Informe de {{name}} listo',
    coach_report_ready_body: 'Toca para ver el informe',
    coach_digest_title: '☀️ Tu día de coach',
    digest_reports_one: '{{n}} análisis por validar',
    digest_reports_many: '{{n}} análisis por validar',
    digest_media_one: '{{n}} nuevo archivo',
    digest_media_many: '{{n}} nuevos archivos',
    digest_messages_one: '{{n}} mensaje',
    digest_messages_many: '{{n}} mensajes',
    digest_inactive_one: '{{n}} alumno inactivo',
    digest_inactive_many: '{{n}} alumnos inactivos',

    welcome_day0: '¡Bienvenido a bordo! 💪 Me alegra mucho acompañarte. Tómate tu tiempo para descubrir la app con calma y, sobre todo, escríbeme aquí en cuanto tengas una pregunta: estoy aquí para ti. ¡Avanzamos juntos!',
    welcome_day2: '¡Hola! Espero que te estés adaptando bien 😊 Recuerda completar tu cuestionario y registrar tus primeras comidas y entrenamientos: cuanto más sepa de ti, mejor podré adaptar tu seguimiento. ¡Hasta pronto!',
    welcome_day7: '¡Ya llevamos una semana juntos! 🎉 Cuéntame cómo te sientes: tu energía, tus comidas, tus sesiones… Cuéntamelo todo, hacemos un primer balance y ajustamos lo que haga falta.',

    checkin_label_mood: 'Ánimo',
    checkin_label_energy: 'Energía',
    checkin_label_sleep: 'Sueño (h/noche)',
    checkin_label_weight: 'Peso',
    checkin_label_notes: 'Notas',

    err_too_many_requests: 'Demasiadas solicitudes, inténtalo de nuevo en un momento',
    err_too_many_attempts: 'Demasiados intentos, inténtalo de nuevo en un minuto',
    err_too_many_signups: 'Demasiadas cuentas creadas desde esta IP',
    err_too_many_resets: 'Demasiadas solicitudes, inténtalo de nuevo en una hora',
    err_email_send: 'Error al enviar el email. Inténtalo de nuevo en unos instantes.',
    err_generation: 'No se pudo generar, inténtalo de nuevo.',
    coach_managed_ai: 'Tienes un coach — contáctalo directamente.',
    coach_managed_nutrition: 'Tu coach gestiona tu programa nutricional.',
    coach_managed_muscu: 'Tu coach gestiona tu programa de entrenamiento.',
    coach_managed_recipes: 'Tu coach gestiona tus recetas.',
    coach_required_report: 'Pide tu informe a tu coach.',
  },
};

// pushText('en', 'reminder_streak_title', { streak: 5 }) → '🔥 Your 5-day streak is on the line!'
// Fallback : langue inconnue → fr ; clé absente dans la langue → fr ; clé inconnue → la clé.
export function pushText(lang, key, vars = {}) {
  const dict = PUSH_TEXTS[lang] || PUSH_TEXTS.fr;
  const template = dict[key] ?? PUSH_TEXTS.fr[key] ?? key;
  return String(template).replace(/\{\{(\w+)\}\}/g, (_, k) => (vars[k] ?? ''));
}

// Alias sémantique pour les messages d'erreur destinés à l'affichage utilisateur.
export const errorText = pushText;
